# Generated by Django 4.2.3 on 2023-07-27 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Otpcode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('phone_number', models.CharField(max_length=11)),
                ('expires_at', models.DateTimeField()),
            ],
        ),
    ]
