# Generated by Django 4.2.3 on 2023-07-27 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_otpcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='otpcode',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
