# Generated by Django 4.2.3 on 2023-08-14 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_token',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
