# Generated by Django 4.2.3 on 2023-08-09 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_food_created_food_sells'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='foods_number',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
