# Generated by Django 4.2.3 on 2023-08-14 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_order_order_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_token',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
