# Generated by Django 4.2.3 on 2023-08-09 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_category_foods_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
